apiVersion: apps/v1
kind: Deployment
metadata:
  name: evo-ai-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: evo-ai
  template:
    metadata:
      labels:
        app: evo-ai
    spec:
      containers:
        - name: evo-ai
          image: vedant3530/evo-ai:latest
          imagePullPolicy: Always